package pij.main;

import pij.main.Move.Direction;
import pij.main.dictionary.Dictionary;

public class Computer extends Player {

    public Computer(Rack rack, Dictionary dictionary) {
        super(rack, dictionary);
    }

    /**
     * Generates and returns the Move generated by the Computer player.
     * @return Move of Computer player
     */
    public Move chooseMove(final Board board) {

        for (int i = 0; i < board.getSize(); i++) {
            getMoveForArray(i, Direction.right, board);
            getMoveForArray(i, Direction.down, board);
        }

        Move move = Move.fromString(",,");
        return move;
    }

    private Move getMoveForArray(
            final int array, final Direction direction, final Board board) {
        Move move = null;
        String testLetters = "ABCDEFG";
        //String fmt = "array: index: %d, direction: %s";
        //System.out.println(String.format(fmt, array, direction));

        for (int i = 0; i < board.getSize(); i++) {
            Position position = switch (direction) {
                case right -> Position.fromIndices(array, i);
                case down -> Position.fromIndices(i, array);
            };
            Move testMove = new WordMove(testLetters, position, direction);
            boolean validStart = board.checkStart(testMove);
            if (validStart) {
                System.out.println("Maybe I go, " + direction
                        + " here...: " + position);
                String rackLetters;
            }
        }

        return move;
    }

}
